# Generated by Django 4.0.2 on 2022-02-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_predmeti'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='token',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
