# Generated by Django 4.0.2 on 2022-02-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_answers_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='token',
        ),
    ]
